# Generated by Django 3.2.5 on 2021-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
            ],
        ),
    ]
